### ISSUE TITLE
Installation process....

### ISSUE THREAD

**Issue by codeclinic** [hubertnguyen/memcachier#2]
Hi,

Ive dropped 'object-cache.php' in to '/wp-content/' and added my credentials into 'wp-config.php'.
However, I'm not seeing any usage in the Memcachier dashboard.

Do we need to do anything to get this working? Some sort of plugin, etc?

Thanks.

**Comment by hubertnguyen** [comment]
'object-cache.php is the only thing you need.

Now, it's possible that there is an issue with the credentials. Usually, I can see it's working because the # of MySQL calls drops like a stone. Maybe I'll upload a little program to test your credentials as a stand-alone PHP file.

Could you copy/paste how you've entered the credentials in wp-contig.php (just those 2-3 lines) -- WITHOUT showing your credentials?

Also, make 100% sure that you add these lines _ABOVE_ these lines

// -- Memcache credentials HERE--

/*\* Absolute path to the WordPress directory. */
if ( !defined('ABSPATH') )

**Comment by codeclinic** [comment]
Ill copy that info over shortly.

However, right now the site is giving me this error:

Fatal error: Class 'Memcache' not found in /home/dev/public_html/wp-content/object-cache.php on line 289

**Comment by codeclinic** [comment]
/\* MEMCACHIER CREDENTIALS */
global $memcached_servers; 
$memcached_servers = array('default' => array('serverxxxxxx:11211')); 
define('MEMCACHIER_USER', 'xxxxxxx'); 
define('MEMCACHIER_PASSWORD', 'xxxxxxxxx');

**Comment by hubertnguyen** [comment]
OK, that looks ok. From your other thread, it looks like you're missing the PHP Memcache library for now

**Comment by codeclinic** [comment]
Agreed, thanks.
